### ISSUE TITLE
Update GitHub Actions workflow to build Docker images

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/osmp#63]
All necessary services should actually have images built on CI and pushed to GitHub Container Registry. The permission control will inherit from this repository, but they should be made public to not consume GitHub Free quotas.

Example job body:
```yaml
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=${{ github.ref == 'refs/heads/master' }}
          tags: |
            type=ref,event=tag
            type=sha,format=long
      - uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: BOT_REVISION=${{ github.sha }}
          pull: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
 ```
